### ISSUE TITLE
Add SQL scripts to repo

### ISSUE THREAD

**Issue by testlnord** [LizaTretyakova/QuestionAnsweringSystem#1]
Please, add sql scripts for creating database to master branch.

**Comment by N-buga** [comment]
Okey, I've done.

**Comment by testlnord** [comment]
how about moving them to master? )

**Comment by LizaTretyakova-zz** [comment]
We are going to create a new branch first, merge our code there and then push the result to master :)

**Comment by testlnord** [comment]
Looking forward to see it.

**Comment by LizaTretyakova-zz** [comment]
New branch is called `common`, there are all basic files, but implementations of attributes extractions are temporary (and should be rewritten eventually) and dispatcher is absent (because it's meant to be added by Nadya). Seemingly all sql-scripts will be in `database_wrappers.py` in wrappers.
